version: '3'

services:
  postgresql:
    image: postgres:13.3-alpine
    container_name: "quarkus-games-psql"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mcgames-dev