version: '3'

services:
  postgresql:
    image: postgres:13.3-alpine
    container_name: "quarkus-games-psql"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mcgames-dev

  redis:
    image: 'redis:6-alpine'
    container_name: redis-cache
    ports:
      - '6379:6379'

  jaeger:
    image: 'jaegertracing/all-in-one:latest'
    container_name: "jaeger"
    ports:
      - '5775:5775/udp'
      - '6831:6831/udp'
      - '6832:6832/udp'
      - '5778:5778'
      - '14268:14268'
      - '14250:14250'
      - '16686:16686'
    expose:
      - '5775'
      - '6831'
      - '6832'
      - '5778'
      - '14268'
      - '14250'
      - '16686'