quarkus:
  profile: dev
  application:
    name: mcgames
  shutdown:
    timeout: 5
  banner:
    enabled: false
  http:
    port: 8090
  datasource:
    db-kind: postgresql
    jdbc:
      url: jdbc:tracing:postgresql://localhost:5432/mcgames-dev
      driver: io.opentracing.contrib.jdbc.TracingDriver
    username: postgres
    password: postgres
  hibernate-orm:
    database:
      generation: none
  liquibase:
    migrate-at-start: true
    change-log: "classpath:liquibase/changelog.yml"
  jaeger:
    enabled: true
    service-name: ${quarkus.application.name}-${quarkus.profile}
    reporter-log-spans: false
    endpoint: http://localhost:14268/api/traces
    sampler-type: const
    sampler-param: 1
  redis:
    hosts: redis://localhost:6379
    client-type: standalone
    max-pool-size: 12
    max-pool-waiting: 64
  log:
    console:
      enable: true
      level: INFO
      format: "%d{HH:mm:ss} %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n"