quarkus:
  profile: ${QUARKUS_PROFILE:dev}
  application:
    name: ${QUARKUS_APP_NAME:mcgames}
  shutdown:
    timeout: 5
  banner:
    enabled: false
  http:
    port: ${QUARKUS_HTTP_PORT:8090}
  datasource:
    db-kind: ${QUARKUS_DATASOURCE_KIND:postgresql}
    jdbc:
      url: ${QUARKUS_DATASOURCE_JDBC_URL:jdbc:tracing:postgresql://localhost:5432/mcgames-dev}
      driver: ${QUARKUS_DATASOURCE_JDBC_DRIVER:io.opentracing.contrib.jdbc.TracingDriver}
    username: ${QUARKUS_DATASOURCE_USERNAME:postgres}
    password: ${QUARKUS_DATASOURCE_PASSWORD:postgres}
  hibernate-orm:
    database:
      generation: none
  liquibase:
    migrate-at-start: true
    change-log: "classpath:liquibase/changelog.yml"
  jaeger:
    enabled: ${QUARKUS_JEAGER_ENABLED:true}
    service-name: ${quarkus.application.name}-${quarkus.profile}
    reporter-log-spans: false
    endpoint: ${QUARKUS_JEAGER_ENDPOINT:http://localhost:14268/api/traces}
    sampler-type: const
    sampler-param: 1
  redis:
    hosts: redis://localhost:6379
    client-type: standalone
    max-pool-size: 12
    max-pool-waiting: 64
  log:
    console:
      enable: true
      level: INFO
      format: "%d{HH:mm:ss} %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n"